# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import blackjack_pb2 as blackjack__pb2


class BlackjackServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.makeADecision = channel.unary_unary(
        '/BlackjackService/makeADecision',
        request_serializer=blackjack__pb2.BoardState.SerializeToString,
        response_deserializer=blackjack__pb2.MLDecision.FromString,
        )
    self.GetDigestor = channel.unary_unary(
        '/BlackjackService/GetDigestor',
        request_serializer=blackjack__pb2.DigestMessage.SerializeToString,
        response_deserializer=blackjack__pb2.DigestedMessage.FromString,
        )


class BlackjackServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def makeADecision(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDigestor(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BlackjackServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'makeADecision': grpc.unary_unary_rpc_method_handler(
          servicer.makeADecision,
          request_deserializer=blackjack__pb2.BoardState.FromString,
          response_serializer=blackjack__pb2.MLDecision.SerializeToString,
      ),
      'GetDigestor': grpc.unary_unary_rpc_method_handler(
          servicer.GetDigestor,
          request_deserializer=blackjack__pb2.DigestMessage.FromString,
          response_serializer=blackjack__pb2.DigestedMessage.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'BlackjackService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
