# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blackjack.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='blackjack.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0f\x62lackjack.proto\"*\n\x04\x43\x61rd\x12\x13\n\x04suit\x18\x01 \x01(\x0e\x32\x05.Suit\x12\r\n\x05value\x18\x02 \x01(\x05\"\x1b\n\x04Hand\x12\x13\n\x04hand\x18\x01 \x03(\x0b\x32\x05.Card\"t\n\nBoardState\x12\x19\n\ndealerHand\x18\x01 \x01(\x0b\x32\x05.Hand\x12\x17\n\x0f\x64\x65\x61lerScoreList\x18\x02 \x03(\x05\x12\x19\n\nplayerHand\x18\x03 \x01(\x0b\x32\x05.Hand\x12\x17\n\x0fplayerScoreList\x18\x04 \x03(\x05\"y\n\nMLDecision\x12&\n\x08\x64\x65\x63ision\x18\x01 \x01(\x0e\x32\x14.MLDecision.Decision\"C\n\x08\x44\x65\x63ision\x12\x07\n\x03HIT\x10\x00\x12\t\n\x05STAND\x10\x01\x12\r\n\tDOUBLDOWN\x10\x02\x12\t\n\x05SPLIT\x10\x03\x12\t\n\x05OTHER\x10\x04\"!\n\rDigestMessage\x12\x10\n\x08ToDigest\x18\x01 \x01(\t\"8\n\x0f\x44igestedMessage\x12\x10\n\x08\x44igested\x18\x01 \x01(\t\x12\x13\n\x0bWasDigested\x18\x02 \x01(\x08*7\n\x04Suit\x12\n\n\x06SPADES\x10\x00\x12\n\n\x06HEARTS\x10\x01\x12\x0c\n\x08\x44IAMONDS\x10\x02\x12\t\n\x05\x43LUBS\x10\x03\x32r\n\x10\x42lackjackService\x12+\n\rmakeADecision\x12\x0b.BoardState\x1a\x0b.MLDecision\"\x00\x12\x31\n\x0bGetDigestor\x12\x0e.DigestMessage\x1a\x10.DigestedMessage\"\x00\x62\x06proto3')
)

_SUIT = _descriptor.EnumDescriptor(
  name='Suit',
  full_name='Suit',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SPADES', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HEARTS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIAMONDS', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLUBS', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=426,
  serialized_end=481,
)
_sym_db.RegisterEnumDescriptor(_SUIT)

Suit = enum_type_wrapper.EnumTypeWrapper(_SUIT)
SPADES = 0
HEARTS = 1
DIAMONDS = 2
CLUBS = 3


_MLDECISION_DECISION = _descriptor.EnumDescriptor(
  name='Decision',
  full_name='MLDecision.Decision',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HIT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STAND', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DOUBLDOWN', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SPLIT', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OTHER', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=264,
  serialized_end=331,
)
_sym_db.RegisterEnumDescriptor(_MLDECISION_DECISION)


_CARD = _descriptor.Descriptor(
  name='Card',
  full_name='Card',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='suit', full_name='Card.suit', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Card.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=61,
)


_HAND = _descriptor.Descriptor(
  name='Hand',
  full_name='Hand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hand', full_name='Hand.hand', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=90,
)


_BOARDSTATE = _descriptor.Descriptor(
  name='BoardState',
  full_name='BoardState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dealerHand', full_name='BoardState.dealerHand', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dealerScoreList', full_name='BoardState.dealerScoreList', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='playerHand', full_name='BoardState.playerHand', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='playerScoreList', full_name='BoardState.playerScoreList', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=208,
)


_MLDECISION = _descriptor.Descriptor(
  name='MLDecision',
  full_name='MLDecision',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='decision', full_name='MLDecision.decision', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MLDECISION_DECISION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=331,
)


_DIGESTMESSAGE = _descriptor.Descriptor(
  name='DigestMessage',
  full_name='DigestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ToDigest', full_name='DigestMessage.ToDigest', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=333,
  serialized_end=366,
)


_DIGESTEDMESSAGE = _descriptor.Descriptor(
  name='DigestedMessage',
  full_name='DigestedMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Digested', full_name='DigestedMessage.Digested', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='WasDigested', full_name='DigestedMessage.WasDigested', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=368,
  serialized_end=424,
)

_CARD.fields_by_name['suit'].enum_type = _SUIT
_HAND.fields_by_name['hand'].message_type = _CARD
_BOARDSTATE.fields_by_name['dealerHand'].message_type = _HAND
_BOARDSTATE.fields_by_name['playerHand'].message_type = _HAND
_MLDECISION.fields_by_name['decision'].enum_type = _MLDECISION_DECISION
_MLDECISION_DECISION.containing_type = _MLDECISION
DESCRIPTOR.message_types_by_name['Card'] = _CARD
DESCRIPTOR.message_types_by_name['Hand'] = _HAND
DESCRIPTOR.message_types_by_name['BoardState'] = _BOARDSTATE
DESCRIPTOR.message_types_by_name['MLDecision'] = _MLDECISION
DESCRIPTOR.message_types_by_name['DigestMessage'] = _DIGESTMESSAGE
DESCRIPTOR.message_types_by_name['DigestedMessage'] = _DIGESTEDMESSAGE
DESCRIPTOR.enum_types_by_name['Suit'] = _SUIT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Card = _reflection.GeneratedProtocolMessageType('Card', (_message.Message,), {
  'DESCRIPTOR' : _CARD,
  '__module__' : 'blackjack_pb2'
  # @@protoc_insertion_point(class_scope:Card)
  })
_sym_db.RegisterMessage(Card)

Hand = _reflection.GeneratedProtocolMessageType('Hand', (_message.Message,), {
  'DESCRIPTOR' : _HAND,
  '__module__' : 'blackjack_pb2'
  # @@protoc_insertion_point(class_scope:Hand)
  })
_sym_db.RegisterMessage(Hand)

BoardState = _reflection.GeneratedProtocolMessageType('BoardState', (_message.Message,), {
  'DESCRIPTOR' : _BOARDSTATE,
  '__module__' : 'blackjack_pb2'
  # @@protoc_insertion_point(class_scope:BoardState)
  })
_sym_db.RegisterMessage(BoardState)

MLDecision = _reflection.GeneratedProtocolMessageType('MLDecision', (_message.Message,), {
  'DESCRIPTOR' : _MLDECISION,
  '__module__' : 'blackjack_pb2'
  # @@protoc_insertion_point(class_scope:MLDecision)
  })
_sym_db.RegisterMessage(MLDecision)

DigestMessage = _reflection.GeneratedProtocolMessageType('DigestMessage', (_message.Message,), {
  'DESCRIPTOR' : _DIGESTMESSAGE,
  '__module__' : 'blackjack_pb2'
  # @@protoc_insertion_point(class_scope:DigestMessage)
  })
_sym_db.RegisterMessage(DigestMessage)

DigestedMessage = _reflection.GeneratedProtocolMessageType('DigestedMessage', (_message.Message,), {
  'DESCRIPTOR' : _DIGESTEDMESSAGE,
  '__module__' : 'blackjack_pb2'
  # @@protoc_insertion_point(class_scope:DigestedMessage)
  })
_sym_db.RegisterMessage(DigestedMessage)



_BLACKJACKSERVICE = _descriptor.ServiceDescriptor(
  name='BlackjackService',
  full_name='BlackjackService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=483,
  serialized_end=597,
  methods=[
  _descriptor.MethodDescriptor(
    name='makeADecision',
    full_name='BlackjackService.makeADecision',
    index=0,
    containing_service=None,
    input_type=_BOARDSTATE,
    output_type=_MLDECISION,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetDigestor',
    full_name='BlackjackService.GetDigestor',
    index=1,
    containing_service=None,
    input_type=_DIGESTMESSAGE,
    output_type=_DIGESTEDMESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BLACKJACKSERVICE)

DESCRIPTOR.services_by_name['BlackjackService'] = _BLACKJACKSERVICE

# @@protoc_insertion_point(module_scope)
